export type Teacher = {
  id: string;
  full_name: string;
  department: string;
  designation: string;
  employee_id: string;
  date_of_last_promotion: string;
  grade_pay: string;
  current_address: string;
  permenent_address: string;
  phone_number: number;
  email: string;
  degree: string;
  specialization: string;
  university: string;
  year_of_passing: string;
  percentage: number;
  language_known: string;
  current_administrative_role: string;
  teaching_experience: number;
  areas_of_specialization: string;
  current_teaching_load: string;
  course_name: string;
  level: "ug" | "pg" | "phd";
 teaching_modality: "online" | "offline" | "hybrid";
 periods_allocated: number;
 periods_engaged: number;
 innovative_teaching_methods: ("moodle" | "online_quizzes" | "video_lectures" | "virtual_lab")[];
 methodolology_details: string;
 hours_spent_on_supervision: number;
 number_of_students_supervised: number;
 paper_title: string;
 journal_name: string;
 issn_isbn: string;
impact_factor: number;
number_of_authors: number;
project_title: string;
funding_agency: string;
grant_amount: number;
patent_title: string;
status: "filed" | "granted" ;
activity_type:"remedial classes"|"carreer guidance"|"counseling"|"mentoring"|"workshop";
hours_spent : number;
activity_type_2:"remedial classes"|"carreer guidance"|"counseling"|"mentoring"|"workshop";
hours_spent_2 : number;
awardfellowship_title: string;
learning_level: "national" | "international" | "state" ;
lecture_title: string;
lecture_details: string;
lecture_level: "national" | "international" | "state" ;
content_type: "text" | "video" | "audio" | "presentation" | "other";
content_url: string;
};
